routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\Auth::user()){
        if (\Illuminate\Support\Facades\Auth::user()->role == 1){

            return redirect()->route('dashboard.index');
        }elseif (\Illuminate\Support\Facades\Auth::user()->role == 4){
            return redirect()->route('groups.index');

        }else{
            return view('welcome');
        }

    }else{
        return redirect()->route('login');

    }
});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);
        Route::resource('sms', \App\Http\Controllers\SmsController::class);
    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

        Route::resource('salaries', \App\Http\Controllers\SalaryController::class)->only([
            'index','store','destroy'
        ]);



        Route::resource('tests', \App\Http\Controllers\TestController::class);
        Route::resource('results', \App\Http\Controllers\ResultController::class);
        Route::resource('sms_services', \App\Http\Controllers\SmsServiceController::class);
        Route::resource('sms', \App\Http\Controllers\SmsController::class)->only([
            'index'
        ]);
        Route::resource('kassas', \App\Http\Controllers\KassaController::class);

    });



    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

    });

    ///// Teacher routes /////
    Route::group(['prefix'=>'admin','middleware'=>'teacher'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);
        Route::resource('teachers', \App\Http\Controllers\TeacherController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('workers', \App\Http\Controllers\WorkersController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('attendances', \App\Http\Controllers\AttendanceController::class);
        Route::get('attendances/{s_id}/{g_id}',[\App\Http\Controllers\AttendanceController::class,'show'])->name('attendances.show_two');

        Route::resource('dashboard', \App\Http\Controllers\DashboardController::class)->only([
            'index'
        ]);

    });



    Route::resource('rooms', \App\Http\Controllers\RoomController::class);
    Route::resource('sciences', \App\Http\Controllers\ScienceController::class);
    Route::resource('lids', \App\Http\Controllers\LidController::class);
    Route::resource('lid_students', \App\Http\Controllers\LidStudentController::class);
    Route::resource('students', \App\Http\Controllers\StudentsController::class);
    Route::resource('courses', \App\Http\Controllers\CourseController::class);
    Route::resource('groups', \App\Http\Controllers\GroupController::class);
    Route::resource('student_groups', \App\Http\Controllers\StudentGroupController::class);
    Route::resource('graphics', \App\Http\Controllers\GraphicController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);

    Route::post('graphic_sms/{graphic_id}', [\App\Http\Controllers\GraphicController::class, 'graphic_sms'])->name('graphic.sms');
    Route::get('graphic_full_sms', [\App\Http\Controllers\GraphicController::class, 'graphic_full_sms'])->name('graphic_full.sms');
    Route::post('group_sms', [\App\Http\Controllers\GroupController::class, 'group_sms'])->name('group.sms');
    Route::post('students_sms', [\App\Http\Controllers\StudentsController::class, 'students_sms'])->name('students.sms');
    Route::get('status_group/{group_id}', [\App\Http\Controllers\GroupController::class, 'status_group'])->name('status.group');
    Route::get('result/export/{test_id}', [\App\Http\Controllers\ResultController::class, 'export'])->name('results.export');
    Route::get('salaries/export', [\App\Http\Controllers\SalaryController::class, 'export'])->name('salaries.export');
    Route::get('payment/export', [\App\Http\Controllers\PaymentController::class, 'export'])->name('payment.export');
    Route::get('graphic/export', [\App\Http\Controllers\GraphicController::class, 'export'])->name('graphics.export');
    Route::get('group/export/{group_id}', [\App\Http\Controllers\GroupController::class, 'export'])->name('group.export');
    Route::get('student/export', [\App\Http\Controllers\StudentsController::class, 'export'])->name('student.export');
    Route::post('student/import', [\App\Http\Controllers\StudentsController::class, 'import'])->name('student.import');
});

Route::get('lang/change', [\App\Http\Controllers\LangController::class, 'change'])->name('changeLang');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('form', App\Http\Controllers\FormController::class);

Route::get('payment_check/{id}', [\App\Http\Controllers\PaymentController::class,'payment_check'])->name('payment_check');







//handle requests from payment system
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

//redirect to payment system or payment form
Route::any('/pay/{paysys}/{key}/{amount}',function($paysys, $key, $amount){
    $model = Goodoneuz\PayUz\Services\PaymentService::convertKeyToModel($key);
    $url = request('redirect_url','/'); // redirect url after payment completed
    $pay_uz = new Goodoneuz\PayUz\PayUz;
    $pay_uz
        ->driver($paysys)
        ->redirect($model, $amount, 860, $url);
})->name('click');

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $table = 'attendances';

    protected $fillable = [
        'student_id',
        'group_id',
        'date',
        'status'
    ];
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Attendance;
use App\Models\Group;
use App\Models\Sms;
use App\Models\Students;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'status'=>'required'
        ]);

        $list = [];
        $array = $request->status;
        foreach ($array as $key => $item){
                $list[] = explode(',',$item);
        }

        $array_obj = [];

        foreach ($list as $key => $item){
            $object = new \stdClass();
            $object->status = $item[0];
            $object->student_id = $item[1];
            $object->group_id = $item[2];
            $object->date = $item[3];
            $array_obj[$key] = $object;
        }


        foreach ($array_obj as $item){
            $attend = Attendance::firstOrNew([
                'student_id'=>$item->student_id,
                'group_id'=>$item->group_id,
                'date'=>$item->date
            ])
                ->where('student_id','=',$item->student_id)
                ->where('group_id','=',$item->group_id)
                ->where('date','=',$item->date)
                ->first();
            if ($attend){
                $attend->status = $item->status;
                $attend->student_id = $item->student_id;
                $attend->group_id = $item->group_id;
                $attend->date = date('Y-m-d',strtotime($item->date));
                $attend->save();
            }else{
                $attend = new Attendance();
                $attend->status = $item->status;
                $attend->student_id = $item->student_id;
                $attend->group_id = $item->group_id;
                $attend->date =  date('Y-m-d',strtotime($item->date));
                $attend->save();
            }

            if ($request->sms){
                $student = Students::find($item->student_id);
                $group = Group::find($item->group_id);

                $date =  \Illuminate\Support\Carbon::now()->setTimezone('Asia/Tashkent')->format('Y-m-d H:i:s');

                $sms_text = "Dars qoldirildi. Guruh:".$group->name.". ".$group->starts_at."-".$group->ends_at.". Student:".$student->name;

                $sms = Sms::eskiz($student->phone,'Teacher: '.Auth::user()->name.' -- '.$sms_text);
                Sms::eskiz($student->parent_phone,'Teacher: '.Auth::user()->name.' -- '.$sms_text);

                $json = json_decode($sms);
                if ($json->status == 'waiting'){
                    Sms::create([
                        'student_id'=>$student->id,
                        'user_id'=> Auth::user()->id,
                        'text'=>'Teacher: '.Auth::user()->name.' -- '.$sms_text,
                        'date'=>$date,
                        'service'=>'eskiz',
                        'status'=>1
                    ]);
                }else{
                    Sms::create([
                        'student_id'=>$student->id,
                        'user_id'=> Auth::user()->id,
                        'text'=>'Teacher: '.Auth::user()->name.' -- '.$sms_text,
                        'date'=>$date,
                        'service'=>'eskiz',
                        'status'=>0
                    ]);
                }
            }

        }


        return redirect()->back()->withErrors([
            'success'=>__('lang.saved'),
        ]);


    }

    /**
     * Display the specified resource.
     *
     * @param  $s_id
     * @param  $g_id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $s_id,$g_id)
    {
        if ($request->per_page){
            $per_page = $request->per_page;
        }else{
            $per_page = 10;
        }

        if ($request->from && $request->to){
            $from = $request->from;
            $to = $request->to;
            $attendances = DB::table('attendances as a')
                ->join('students as s','s.id','=','a.student_id')
                ->select('a.*','s.name')
                ->where('a.student_id','=',$s_id)
                ->where('a.group_id','=',$g_id)
                ->whereBetween('a.date',[$request->from,$request->to])
                ->orderBy('a.date','desc')
                ->paginate($per_page);
        }else{
            $from = date("Y-m-d");
            $to = date("Y-m-d");
            $attendances = DB::table('attendances as a')
                ->join('students as s','s.id','=','a.student_id')
                ->select('a.*','s.name')
                ->where('a.student_id','=',$s_id)
                ->where('a.group_id','=',$g_id)
                ->orderBy('a.date','desc')
                ->paginate($per_page);
        }

        $student = Students::find($s_id);
        $group = Group::find($g_id);

        return view('admin.attendances.show',compact(
            'attendances','per_page','from','to','student','group'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function edit(Attendance $attendance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Attendance $attendance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attendance $attendance)
    {

        $attendance->delete();

        return redirect()->back()
            ->withErrors([
            'success'=>__('lang.deleted'),
        ]);
    }
}

resources/views/admin/attendances/show.blade.php
@extends('layouts.main')

@section('main-content')


    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <a href="{{ route('groups.show',$group->id) }}">
                        <i class="fas fa-long-arrow-left bg-gradient-info p-2 px-3 rounded"></i>
                    </a>
                </li>
                <li>
                    <h3 class="card-title">{{ __('lang.attendance') }} {{ $group->name.' '.$student->name }}</h3>
                </li>
                <li>

                    <!-- SEARCH FORM -->
                    <form action="{{ route('attendances.show_two',[$student->id,$group->id]) }}" method="get" class="form-inline m-0 ml-md-3">
                        @csrf
                        <div class="input-group input-group-sm">
                            <select name="per_page" id="" class="form-control form-control-navbar">
                                <option {{ $per_page == 10 ? 'selected':'' }} value="10">10</option>
                                <option {{ $per_page == 20 ? 'selected':'' }}  value="20">20</option>
                                <option {{ $per_page == 50 ? 'selected':'' }}  value="50">50</option>
                                <option {{ $per_page == 100 ? 'selected':'' }}  value="100">100</option>
                            </select>
                            <input name="from" value="{{ $from }}" class="form-control form-control-navbar" type="date" placeholder="Search" aria-label="Search">
                            <input name="to" value="{{ $to }}" class="form-control form-control-navbar" type="date" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="py-1">N</th>
                    <th class="py-1">{{ __('lang.name') }}</th>
                    <th class="py-1">{{ __('lang.date') }}</th>
                    <th class="py-1">{{ __('lang.status') }}</th>
                    <th class="py-1">
                        {{ __('lang.rights') }}
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($attendances as $attendance)
                <tr>
                    <td class="py-1">
                        {{($attendances->currentpage()-1)*$attendances->perpage()+($loop->index+1)}}
                    </td>
                    <td class="py-1">{{ $attendance->name }}</td>
                    <td class="py-1">{{ $attendance->date }}</td>
                    <td class="py-1">
                        @if($attendance->status == 1)
                            <span class="badge badge-primary">{{ __('lang.reason_text') }}</span>
                        @else
                            <span class="badge badge-warning">{{ __('lang.absent_text') }}</span>
                        @endif
                    </td>
                    <td class="py-1">


                        @if( Auth::user()->role == 1 || Auth::user()->role == 2)

                            <button type="button" class="btn btn-danger my-0 py-0 px-1" data-toggle="modal" data-target="#modal-danger{{ $attendance->id }}">
                                <i class="fas fa-trash m-0 p-0"></i>
                            </button>

                            <div class="modal fade" id="modal-danger{{ $attendance->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger">
                                        <div class="modal-header">
                                            <h4 class="modal-title">{{ __('lang.delete') }}</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>{{ __('lang.delete_message') }}</p>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">{{ __('lang.close') }}</button>
                                                <form class="d-inline" action="{{ route('attendances.destroy',$attendance->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-outline-light">
                                                        {{ __('lang.delete') }}
                                                    </button>
                                                </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->

                        @elseif(date('Y-m-d') == date('Y-m-d',strtotime($attendance->date)))
                            <button type="button" class="btn btn-danger my-0 py-0 px-1" data-toggle="modal" data-target="#modal-danger{{ $attendance->id }}">
                                <i class="fas fa-trash m-0 p-0"></i>
                            </button>

                            <div class="modal fade" id="modal-danger{{ $attendance->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Delete</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure?</p>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                                            <form class="d-inline" action="{{ route('attendances.destroy',$attendance->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-outline-light">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                            @endif

                    </td>
                </tr>

                @endforeach


                </tbody>
            </table>
            <div>{{ $attendances->appends($_GET)->links() }}</div>
        </div>
        <!-- /.card-body -->
@endsection