routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\Auth::user()){
        if (\Illuminate\Support\Facades\Auth::user()->role == 1){

            return redirect()->route('dashboard.index');
        }elseif (\Illuminate\Support\Facades\Auth::user()->role == 4){
            return redirect()->route('groups.index');

        }else{
            return view('welcome');
        }

    }else{
        return redirect()->route('login');

    }
});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);
        Route::resource('sms', \App\Http\Controllers\SmsController::class);
    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

        Route::resource('salaries', \App\Http\Controllers\SalaryController::class)->only([
            'index','store','destroy'
        ]);



        Route::resource('tests', \App\Http\Controllers\TestController::class);
        Route::resource('results', \App\Http\Controllers\ResultController::class);
        Route::resource('sms_services', \App\Http\Controllers\SmsServiceController::class);
        Route::resource('sms', \App\Http\Controllers\SmsController::class)->only([
            'index'
        ]);
        Route::resource('kassas', \App\Http\Controllers\KassaController::class);

    });



    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

    });

    ///// Teacher routes /////
    Route::group(['prefix'=>'admin','middleware'=>'teacher'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);
        Route::resource('teachers', \App\Http\Controllers\TeacherController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('workers', \App\Http\Controllers\WorkersController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('attendances', \App\Http\Controllers\AttendanceController::class);
        Route::get('attendances/{s_id}/{g_id}',[\App\Http\Controllers\AttendanceController::class,'show'])->name('attendances.show_two');

        Route::resource('dashboard', \App\Http\Controllers\DashboardController::class)->only([
            'index'
        ]);

    });



    Route::resource('rooms', \App\Http\Controllers\RoomController::class);
    Route::resource('sciences', \App\Http\Controllers\ScienceController::class);
    Route::resource('lids', \App\Http\Controllers\LidController::class);
    Route::resource('lid_students', \App\Http\Controllers\LidStudentController::class);
    Route::resource('students', \App\Http\Controllers\StudentsController::class);
    Route::resource('courses', \App\Http\Controllers\CourseController::class);
    Route::resource('groups', \App\Http\Controllers\GroupController::class);
    Route::resource('student_groups', \App\Http\Controllers\StudentGroupController::class);
    Route::resource('graphics', \App\Http\Controllers\GraphicController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);

    Route::post('graphic_sms/{graphic_id}', [\App\Http\Controllers\GraphicController::class, 'graphic_sms'])->name('graphic.sms');
    Route::get('graphic_full_sms', [\App\Http\Controllers\GraphicController::class, 'graphic_full_sms'])->name('graphic_full.sms');
    Route::post('group_sms', [\App\Http\Controllers\GroupController::class, 'group_sms'])->name('group.sms');
    Route::post('students_sms', [\App\Http\Controllers\StudentsController::class, 'students_sms'])->name('students.sms');
    Route::get('status_group/{group_id}', [\App\Http\Controllers\GroupController::class, 'status_group'])->name('status.group');
    Route::get('result/export/{test_id}', [\App\Http\Controllers\ResultController::class, 'export'])->name('results.export');
    Route::get('salaries/export', [\App\Http\Controllers\SalaryController::class, 'export'])->name('salaries.export');
    Route::get('payment/export', [\App\Http\Controllers\PaymentController::class, 'export'])->name('payment.export');
    Route::get('graphic/export', [\App\Http\Controllers\GraphicController::class, 'export'])->name('graphics.export');
    Route::get('group/export/{group_id}', [\App\Http\Controllers\GroupController::class, 'export'])->name('group.export');
    Route::get('student/export', [\App\Http\Controllers\StudentsController::class, 'export'])->name('student.export');
    Route::post('student/import', [\App\Http\Controllers\StudentsController::class, 'import'])->name('student.import');
});

Route::get('lang/change', [\App\Http\Controllers\LangController::class, 'change'])->name('changeLang');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('form', App\Http\Controllers\FormController::class);

Route::get('payment_check/{id}', [\App\Http\Controllers\PaymentController::class,'payment_check'])->name('payment_check');







//handle requests from payment system
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

//redirect to payment system or payment form
Route::any('/pay/{paysys}/{key}/{amount}',function($paysys, $key, $amount){
    $model = Goodoneuz\PayUz\Services\PaymentService::convertKeyToModel($key);
    $url = request('redirect_url','/'); // redirect url after payment completed
    $pay_uz = new Goodoneuz\PayUz\PayUz;
    $pay_uz
        ->driver($paysys)
        ->redirect($model, $amount, 860, $url);
})->name('click');

app/Models/Science.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Science extends Model
{
    use HasFactory;
    public $timestamps=false;

    protected $table = 'sciences';
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/ScienceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Science;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use function Symfony\Component\String\s;

class ScienceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->per_page){
            $per_page = $request->per_page;
        }else{
            $per_page = 10;
        }
        if ($request->search){
            $search = $request->search;
            $sciences = DB::table('sciences as s')
                ->leftJoinSub("
                select t.id,t.name,t.science_id, count(sg.id) grs
                from `users` t
                    join `groups` g on t.id = g.teacher_id and g.status = 1
                    join student_groups sg on g.id = sg.group_id
                group by t.id",'tgs','tgs.science_id','=','s.id')
                ->select('s.*',DB::raw('count(tgs.id) as teachers'),
                    DB::raw('sum(tgs.grs) as students'))
                ->where('s.name','like', '%'.$request->search.'%')
                ->groupBy('s.id')
                ->paginate($per_page);
        }else {
            $search = '';
            $sciences = DB::table('sciences as s')
                ->leftJoinSub("
                select t.id,t.name,t.science_id, count(sg.id) grs
                from `users` t
                    join `groups` g on t.id = g.teacher_id and g.status = 1
                    join student_groups sg on g.id = sg.group_id
                group by t.id",'tgs','tgs.science_id','=','s.id')
                ->select('s.*',DB::raw('count(tgs.id) as teachers'),
                DB::raw('sum(tgs.grs) as students'))
                ->groupBy('s.id')
                ->paginate($per_page);
        }


        return view('admin.sciences.index',compact('sciences','search','per_page'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required'
        ]);

        $science = new Science();
        $science->name = $request->name;
        $science->save();

        return redirect()->back()->withErrors([
            'success'=>__('lang.saved'),
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Science  $science
     * @return \Illuminate\Http\Response
     */
    public function show(Science $science)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Science  $science
     * @return \Illuminate\Http\Response
     */
    public function edit(Science $science)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Science  $science
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Science $science)
    {
        $request->validate([
            'name'=>'required'
        ]);

        $science->name = $request->name;
        $science->update();

        return redirect()->back()->withErrors([
            'success'=>__('lang.updated'),
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Science  $science
     * @return \Illuminate\Http\Response
     */
    public function destroy(Science $science)
    {
        try {

            $science->delete();

            return redirect()->back()->withErrors([
                'success'=>__('lang.deleted'),
            ]);
        }catch (\Exception $exception){

            return redirect()->back()->withErrors([
                'error'=>__('lang.cannot_delete'),
            ]);
        }
    }
}

resources/views/admin/sciences/index.blade.php
@extends('layouts.main')

@section('main-content')


    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <h3 class="card-title">{{ __('lang.sciences') }}</h3>
                </li>
                <li>

                    <!-- SEARCH FORM -->
                    <form action="{{ route('sciences.index') }}" method="get" class="form-inline m-0 ml-md-3">
                        @csrf
                        <div class="input-group input-group-sm">
                            <select name="per_page" id="" class="form-control form-control-navbar">
                                <option {{ $per_page == 10 ? 'selected':'' }} value="10">10</option>
                                <option {{ $per_page == 20 ? 'selected':'' }}  value="20">20</option>
                                <option {{ $per_page == 50 ? 'selected':'' }}  value="50">50</option>
                                <option {{ $per_page == 100 ? 'selected':'' }}  value="100">100</option>
                            </select>
                                <input name="search" value="{{ $search }}" class="form-control form-control-navbar" type="search" placeholder="{{ __('lang.search') }}" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="py-1">N</th>
                    <th class="py-1">{{ __('lang.name') }}</th>
                    <th class="py-1">{{ __('lang.teachers') }}</th>
                    <th class="py-1">{{ __('lang.students') }}</th>
                    <th class="py-1">
                        @if(Auth::user()->role == 1 || Auth::user()->role == 2)
                        <button type="button" class="btn btn-success my-0 py-0 px-1" data-toggle="modal" data-target="#admin_add">
                            <i class="fas fa-calendar-plus m-0 p-0"></i>
                        </button>
                        <div class="modal fade" id="admin_add">
                            <div class="modal-dialog">
                                <div class="modal-content bg-success">
                                    <form action="{{ route('sciences.store') }}" method="post" enctype="multipart/form-data">

                                        <div class="modal-header">
                                            <h4 class="modal-title">{{ __('lang.add') }}</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            @csrf
                                            <div class="card-body">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">{{ __('lang.name') }}</label>
                                                    <input name="name" type="text" class="form-control" value="" id="exampleInputEmail1" placeholder="{{ __('lang.type_name') }}">
                                                </div>

                                                <div class="form-check">
                                                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                    <label class="form-check-label" for="exampleCheck1">{{ __('lang.checking') }}</label>
                                                </div>
                                            </div>
                                            <!-- /.card-body -->
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">{{ __('lang.close') }}</button>
                                            <button type="submit" class="btn btn-outline-light">{{ __('lang.save') }}</button>
                                        </div>

                                    </form>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal -->
                        @else
                            {{ __('lang.rights') }}
                        @endif

                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($sciences as $science)
                <tr>
                    <td class="py-1">
                        {{($sciences->currentpage()-1)*$sciences->perpage()+($loop->index+1)}}
                    </td>
                    <td class="py-1">{{ $science->name }}</td>
                    <td class="py-1">{{ $science->teachers }}</td>
                    <td class="py-1">{{ $science->students }}</td>
                    <td class="py-1">


                        @if( Auth::user()->role == 1 || Auth::user()->role == 2)
                            <button type="button" class="btn btn-info my-0 py-0 px-1" data-toggle="modal" data-target="#modal{{ $loop->index+1 }}">
                                <i class="fas fa-edit m-0 p-0"></i>
                            </button>
                            <div class="modal fade" id="modal{{ $loop->index+1 }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-primary">
                                        <form action="{{ route('sciences.update', $science->id) }}" method="post" enctype="multipart/form-data">

                                            <div class="modal-header">
                                                <h4 class="modal-title">{{ __('lang.update') }}</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">

                                                @csrf
                                                @method('PUT')
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">{{ __('lang.name') }}</label>
                                                        <input name="name" type="text" class="form-control" value="{{ $science->name }}" id="exampleInputEmail1" placeholder="{{ __('lang.type_name') }}">
                                                    </div>

                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                        <label class="form-check-label" for="exampleCheck1">{{ __('lang.checking') }}</label>
                                                    </div>
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">{{ __('lang.close') }}</button>
                                                <button type="submit" class="btn btn-outline-light">{{ __('lang.save') }}</button>
                                            </div>

                                        </form>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->


                            <button type="button" class="btn btn-danger my-0 py-0 px-1" data-toggle="modal" data-target="#modal-danger{{ $science->id }}">
                                <i class="fas fa-trash m-0 p-0"></i>
                            </button>

                            <div class="modal fade" id="modal-danger{{ $science->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger">
                                        <div class="modal-header">
                                            <h4 class="modal-title">{{ __('lang.delete') }}</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>{{ __('lang.delete_message') }}</p>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">{{ __('lang.close') }}</button>
                                                <form class="d-inline" action="{{ route('sciences.destroy',$science->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-outline-light">
                                                        {{ __('lang.delete') }}
                                                    </button>
                                                </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->


                            @endif

                    </td>
                </tr>

                @endforeach


                </tbody>
            </table>
            <div>{{ $sciences->appends($_GET)->links() }}</div>
        </div>
        <!-- /.card-body -->
@endsection