routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\Auth::user()){
        if (\Illuminate\Support\Facades\Auth::user()->role == 1){

            return redirect()->route('dashboard.index');
        }elseif (\Illuminate\Support\Facades\Auth::user()->role == 4){
            return redirect()->route('groups.index');

        }else{
            return view('welcome');
        }

    }else{
        return redirect()->route('login');

    }
});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);
        Route::resource('sms', \App\Http\Controllers\SmsController::class);
    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

        Route::resource('salaries', \App\Http\Controllers\SalaryController::class)->only([
            'index','store','destroy'
        ]);



        Route::resource('tests', \App\Http\Controllers\TestController::class);
        Route::resource('results', \App\Http\Controllers\ResultController::class);
        Route::resource('sms_services', \App\Http\Controllers\SmsServiceController::class);
        Route::resource('sms', \App\Http\Controllers\SmsController::class)->only([
            'index'
        ]);
        Route::resource('kassas', \App\Http\Controllers\KassaController::class);

    });



    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

    });

    ///// Teacher routes /////
    Route::group(['prefix'=>'admin','middleware'=>'teacher'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);
        Route::resource('teachers', \App\Http\Controllers\TeacherController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('workers', \App\Http\Controllers\WorkersController::class)->only([
            'index', 'show','edit','update','store','destroy'
        ]);
        Route::resource('attendances', \App\Http\Controllers\AttendanceController::class);
        Route::get('attendances/{s_id}/{g_id}',[\App\Http\Controllers\AttendanceController::class,'show'])->name('attendances.show_two');

        Route::resource('dashboard', \App\Http\Controllers\DashboardController::class)->only([
            'index'
        ]);

    });



    Route::resource('rooms', \App\Http\Controllers\RoomController::class);
    Route::resource('sciences', \App\Http\Controllers\ScienceController::class);
    Route::resource('lids', \App\Http\Controllers\LidController::class);
    Route::resource('lid_students', \App\Http\Controllers\LidStudentController::class);
    Route::resource('students', \App\Http\Controllers\StudentsController::class);
    Route::resource('courses', \App\Http\Controllers\CourseController::class);
    Route::resource('groups', \App\Http\Controllers\GroupController::class);
    Route::resource('student_groups', \App\Http\Controllers\StudentGroupController::class);
    Route::resource('graphics', \App\Http\Controllers\GraphicController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);

    Route::post('graphic_sms/{graphic_id}', [\App\Http\Controllers\GraphicController::class, 'graphic_sms'])->name('graphic.sms');
    Route::get('graphic_full_sms', [\App\Http\Controllers\GraphicController::class, 'graphic_full_sms'])->name('graphic_full.sms');
    Route::post('group_sms', [\App\Http\Controllers\GroupController::class, 'group_sms'])->name('group.sms');
    Route::post('students_sms', [\App\Http\Controllers\StudentsController::class, 'students_sms'])->name('students.sms');
    Route::get('status_group/{group_id}', [\App\Http\Controllers\GroupController::class, 'status_group'])->name('status.group');
    Route::get('result/export/{test_id}', [\App\Http\Controllers\ResultController::class, 'export'])->name('results.export');
    Route::get('salaries/export', [\App\Http\Controllers\SalaryController::class, 'export'])->name('salaries.export');
    Route::get('payment/export', [\App\Http\Controllers\PaymentController::class, 'export'])->name('payment.export');
    Route::get('graphic/export', [\App\Http\Controllers\GraphicController::class, 'export'])->name('graphics.export');
    Route::get('group/export/{group_id}', [\App\Http\Controllers\GroupController::class, 'export'])->name('group.export');
    Route::get('student/export', [\App\Http\Controllers\StudentsController::class, 'export'])->name('student.export');
    Route::post('student/import', [\App\Http\Controllers\StudentsController::class, 'import'])->name('student.import');
});

Route::get('lang/change', [\App\Http\Controllers\LangController::class, 'change'])->name('changeLang');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('form', App\Http\Controllers\FormController::class);

Route::get('payment_check/{id}', [\App\Http\Controllers\PaymentController::class,'payment_check'])->name('payment_check');







//handle requests from payment system
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

//redirect to payment system or payment form
Route::any('/pay/{paysys}/{key}/{amount}',function($paysys, $key, $amount){
    $model = Goodoneuz\PayUz\Services\PaymentService::convertKeyToModel($key);
    $url = request('redirect_url','/'); // redirect url after payment completed
    $pay_uz = new Goodoneuz\PayUz\PayUz;
    $pay_uz
        ->driver($paysys)
        ->redirect($model, $amount, 860, $url);
})->name('click');

resources/views/admin/edit.blade.php
@extends('layouts.main')
@section('main-content')
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header d-flex justify-content-around">
            <h3 class="card-title">{{ __('lang.update') }}</h3>
            <h3 class="card-title">
                {{ number_format(Auth::user()->balance , 0, ',', '.')  }} SUM
            </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('admin.update', Auth::user()->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">{{ __('lang.name') }}</label>
                    <input name="name" type="text" class="form-control" value="{{ $admin->name }}" id="exampleInputEmail1" placeholder="{{ __('lang.type_name') }}">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">{{ __('lang.phone') }}</label>
                    <input name="phone" type="number" class="form-control" value="{{ $admin->phone }}" id="exampleInputEmail1" placeholder="{{ __('lang.type_phone') }}">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">{{ __('lang.email') }}</label>
                    <input name="email" type="email" class="form-control" value="{{ $admin->email }}" id="exampleInputEmail1" placeholder="{{ __('lang.type_email') }}">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">{{ __('lang.password') }}</label>
                    <input name="password" type="text" class="form-control" id="exampleInputPassword1" placeholder="{{ __('lang.type_password') }}" required>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="exampleInputFile">{{ __('lang.image') }}</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input name="image" id="imgInp" onchange="preview(frame)" type="file" class="custom-file-input" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">{{ __('lang.select') }}</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">{{ __('lang.image') }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <label class="mb-2" for="rasm"><b>{{ __('lang.image') }}</b></label>
                        <img id="frame" class="ml-2" src="{{asset('storage/app/public/images/'.$admin->image)}}" width="100px" height="100px" alt="{{ __('lang.image') }}"/>
                    </div>
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                    <label class="form-check-label" for="exampleCheck1">{{ __('lang.checking') }}</label>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">{{ __('lang.save') }}</button>
            </div>
        </form>
    </div>
    <!-- /.card -->
@endsection